// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newMeasure.proto

package MeasureHR;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeasureHR.Empty)
    com.google.protobuf.MessageOrBuilder {
}
