// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newMeasure.proto

package MeasureHR;

public final class heartRateImpl {
  private heartRateImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeasureHR_rateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeasureHR_rateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeasureHR_rateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeasureHR_rateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeasureHR_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeasureHR_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020newMeasure.proto\022\tMeasureHR\"/\n\013rateReq" +
      "uest\022\023\n\013currentRate\030\001 \001(\t\022\013\n\003bpm\030\002 \001(\005\"<" +
      "\n\014rateResponse\022\027\n\017responseMessage\030\001 \001(\t\022" +
      "\023\n\013responseNum\030\002 \001(\005\"\007\n\005Empty2O\n\013measure" +
      "Rate\022@\n\013displayRate\022\026.MeasureHR.rateRequ" +
      "est\032\027.MeasureHR.rateResponse\"\000B\021B\rheartR" +
      "ateImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MeasureHR_rateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MeasureHR_rateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeasureHR_rateRequest_descriptor,
        new java.lang.String[] { "CurrentRate", "Bpm", });
    internal_static_MeasureHR_rateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MeasureHR_rateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeasureHR_rateResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseNum", });
    internal_static_MeasureHR_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MeasureHR_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeasureHR_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
