// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newMeasure.proto

package MeasureHR;

public interface rateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeasureHR.rateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentRate = 1;</code>
   */
  java.lang.String getCurrentRate();
  /**
   * <code>string currentRate = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentRateBytes();

  /**
   * <code>int32 bpm = 2;</code>
   */
  int getBpm();
}
