// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userLogin.proto

package grpc.user;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Empty)
    com.google.protobuf.MessageOrBuilder {
}
